"""
Data models used across all functions.

Each model is a plain dataclass that can serialise to/from Azure Table Storage
entities (dict[str, str | int | float]) and to JSON-friendly dicts for the API.
"""

from __future__ import annotations

import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id() -> str:
    return uuid.uuid4().hex[:12]


# ── Cost Record ──────────────────────────────────────────────────────────────

@dataclass
class CostRecord:
    """A single cost data point aggregated per day / resource-group / service."""

    date: str                      # YYYY-MM-DD
    subscription_id: str
    resource_group: str
    service_name: str
    cost: float                    # pre-tax cost in billing currency
    currency: str = "USD"
    environment: str = ""          # from tag
    team: str = ""                 # from tag
    record_id: str = field(default_factory=_new_id)
    collected_at: str = field(default_factory=_utcnow)

    # Azure Table Storage keys
    @property
    def partition_key(self) -> str:
        return self.subscription_id

    @property
    def row_key(self) -> str:
        return f"{self.date}_{self.resource_group}_{self.service_name}"

    def to_entity(self) -> dict:
        entity = asdict(self)
        entity["PartitionKey"] = self.partition_key
        entity["RowKey"] = self.row_key
        return entity

    def to_dict(self) -> dict:
        return asdict(self)


# ── Waste Resource ───────────────────────────────────────────────────────────

@dataclass
class WasteResource:
    """A resource identified as idle, orphaned, or underutilised."""

    resource_id: str
    resource_type: str             # e.g. Microsoft.Compute/disks
    resource_name: str
    resource_group: str
    subscription_id: str
    waste_type: str                # unattached_disk | oversized_vm | idle_lb | unused_pip | empty_rg | idle_nsg
    estimated_monthly_savings: float
    details: str = ""
    detected_at: str = field(default_factory=_utcnow)
    record_id: str = field(default_factory=_new_id)

    @property
    def partition_key(self) -> str:
        return self.subscription_id

    @property
    def row_key(self) -> str:
        return f"{self.waste_type}_{self.record_id}"

    def to_entity(self) -> dict:
        entity = asdict(self)
        entity["PartitionKey"] = self.partition_key
        entity["RowKey"] = self.row_key
        return entity

    def to_dict(self) -> dict:
        return asdict(self)


# ── Advisor Recommendation ────────────────────────────────────────────────────

@dataclass
class AdvisorRecommendation:
    """An Azure Advisor cost-optimization recommendation."""

    recommendation_id: str
    category: str                  # Cost
    impact: str                    # High | Medium | Low
    impacted_resource: str
    impacted_resource_type: str
    description: str
    estimated_annual_savings: float
    action: str = ""
    subscription_id: str = ""
    fetched_at: str = field(default_factory=_utcnow)

    @property
    def partition_key(self) -> str:
        return self.subscription_id

    @property
    def row_key(self) -> str:
        return self.recommendation_id

    def to_entity(self) -> dict:
        entity = asdict(self)
        entity["PartitionKey"] = self.partition_key
        entity["RowKey"] = self.row_key
        return entity

    def to_dict(self) -> dict:
        return asdict(self)


# ── Alert ────────────────────────────────────────────────────────────────────

@dataclass
class CostAlert:
    """An alert generated by the governance system."""

    severity: str                  # critical | warning | info
    title: str
    message: str
    cost_impact: float = 0.0
    source: str = ""               # cost_collector | resource_analyzer | recommendation_fetcher
    alert_id: str = field(default_factory=_new_id)
    created_at: str = field(default_factory=_utcnow)

    @property
    def partition_key(self) -> str:
        return self.severity

    @property
    def row_key(self) -> str:
        return f"{self.created_at}_{self.alert_id}"

    def to_entity(self) -> dict:
        entity = asdict(self)
        entity["PartitionKey"] = self.partition_key
        entity["RowKey"] = self.row_key
        return entity

    def to_dict(self) -> dict:
        return asdict(self)
